WITH [Bulk_Order] AS (
SELECT
H.PRODUCT_ID AS SKU
, TO_CHAR(h.WEEK_START_DATE, 'IW') AS KW
, H.BULK_ORDER_QTY AS BULK_ORDER_QTY
FROM TMP_BUSINESS_LOGICS.FCST_BASE_WEEKLY_HISTORY H
ORDER BY H.PRODUCT_ID ASC, TO_CHAR(h.WEEK_START_DATE, 'IW') ASC
)
,
[Outlier_Correction] AS (
SELECT
H.PRODUCT_ID AS SKU
, TO_CHAR(h.WEEK_START_DATE, 'IW') AS KW
, H.OUTLIER_CORRECTION_QTY
FROM TMP_BUSINESS_LOGICS.FCST_BASE_WEEKLY_HISTORY H
)
,
[OOS_CORRECTION] AS (
SELECT H.PRODUCT_ID AS SKU
, TO_CHAR(h.WEEK_START_DATE, 'IW') AS KW
, h.OOS_CORRECTION_QTY
FROM TMP_BUSINESS_LOGICS.FCST_BASE_WEEKLY_HISTORY H
)
SELECT H.PRODUCT_ID
, TO_CHAR(h.WEEK_START_DATE, 'IW') AS KW
, H.NET_QTY
, [Bulk_Order].BULK_ORDER_QTY AS Bulk_Order_Last_KW
, [Outlier_Correction].OUTLIER_CORRECTION_QTY AS OUTLIER_CORRECTION_QTY_LAST_KW
, [OOS_CORRECTION].OOS_CORRECTION_QTY AS OOS_CORRECTION_QTY_LAST_KW
, BCH.SKU_UPLIFT
, BCH.TOP_DOWN_ADJUSTMENT
, CONVERT(DECIMAL(18,2), BCH.MARRIED_FORECAST_QUANTITY) AS SNOP_FCST
, CASE WHEN [Bulk_Order].BULK_ORDER_QTY > 0 AND H.BULK_ORDER_QTY > 0 
				THEN '1' ELSE '0' END 
									AS BULK_ORDER_FAIL
, CASE WHEN BCH.SKU_UPLIFT > 0 
		AND BCH.FORECAST_QUANTITY_AFTER_UPLIFTS_BEFORE_ADJUSTMENT < H.NET_QTY 
			THEN '1' ELSE '0' END AS Uplift_zu_niedrig
, CASE WHEN BCH.TOP_DOWN_ADJUSTMENT > 1
		AND CONVERT(DECIMAL(18,2),BCH.MARRIED_FORECAST_QUANTITY) > BCH.FORECAST_QUANTITY_AFTER_UPLIFTS_BEFORE_ADJUSTMENT 
		AND H.NET_QTY > CONVERT(DECIMAL(18,2),BCH.MARRIED_FORECAST_QUANTITY) 
		THEN '1' ELSE '0' END AS TopDown_Fail
, CASE WHEN h.OOS_CORRECTION_QTY=0 AND [OOS_CORRECTION].OOS_CORRECTION_QTY>0 AND BCH.FORECAST_QUANTITY <  H.NET_QTY 
							THEN '1' ELSE '0' END 
													AS OOS_Correction_Fail
, CASE WHEN  [Outlier_Correction].OUTLIER_CORRECTION_QTY >0 AND H.OUTLIER_CORRECTION_QTY > 0
			THEN  '1' ELSE '0' END 
									AS Outlier_CORRECTION_FAIL
, CASE WHEN ifnull(h.NET_QTY,0) = 0 AND CONVERT(DECIMAL(18,2),BCH.MARRIED_FORECAST_QUANTITY)=0
		THEN '0'
		WHEN ifnull(h.NET_QTY,0)=0 AND CONVERT(DECIMAL(18,2),BCH.MARRIED_FORECAST_QUANTITY)>0
		THEN CONVERT(DECIMAL(18,2),BCH.MARRIED_FORECAST_QUANTITY)
		ELSE ABS(h.NET_QTY-CONVERT(DECIMAL(18,2),BCH.MARRIED_FORECAST_QUANTITY)) END 
																					AS SNOP_MAD
, CASE WHEN ifnull(h.NET_QTY,0) = 0 AND CONVERT(DECIMAL(18,2),BCH.MARRIED_FORECAST_QUANTITY)=0
			THEN '0'
				WHEN ifnull(h.NET_QTY,0)=0 AND CONVERT(DECIMAL(18,2),BCH.MARRIED_FORECAST_QUANTITY)>0
						THEN '9.99'
							ELSE ABS(h.NET_QTY-CONVERT(DECIMAL(18,2),BCH.MARRIED_FORECAST_QUANTITY))/h.NET_QTY
								END
									AS SNOP_MAPE
FROM TMP_BUSINESS_LOGICS.FCST_BASE_WEEKLY_HISTORY H
LEFT JOIN TMP_BUSINESS_LOGICS.SNOP_BASE_CALCULATION_HISTORY BCH
ON H.PRODUCT_ID = BCH.PRODUCT_ID
AND H.WEEK_START_DATE = BCH.WEEK_START_DATE
LEFT JOIN [Bulk_Order]
ON H.PRODUCT_ID = [Bulk_Order].SKU
--Dadurch: Bulk Orders aus der letzten KW
AND TO_CHAR(h.WEEK_START_DATE, 'IW') = [Bulk_Order].KW+1
LEFT JOIN [OOS_CORRECTION]
ON h.PRODUCT_ID = [OOS_CORRECTION].SKU 
--Dadurch: OOS Correction aus der letzten KW
AND TO_CHAR(h.WEEK_START_DATE, 'IW') = [OOS_CORRECTION].KW+1
LEFT JOIN [Outlier_Correction]
ON h.PRODUCT_ID = [Outlier_Correction].SKU
--Dadurch: Outlier Corretction aus der letzten KW
AND TO_CHAR(h.WEEK_START_DATE, 'IW') = [Outlier_Correction].KW+1
WHERE BCH.AS_OF_DATE = BCH.WEEK_START_DATE
AND CASE WHEN ifnull(h.NET_QTY,0) = 0 AND CONVERT(DECIMAL(18,2),BCH.MARRIED_FORECAST_QUANTITY)=0
			THEN '0' WHEN ifnull(h.NET_QTY,0)=0 AND CONVERT(DECIMAL(18,2),BCH.MARRIED_FORECAST_QUANTITY)>0
						THEN '9.99'
						ELSE ABS(h.NET_QTY-CONVERT(DECIMAL(18,2),BCH.MARRIED_FORECAST_QUANTITY))/h.NET_QTY
						END >0.1
AND CASE WHEN ifnull(h.NET_QTY,0) = 0 AND CONVERT(DECIMAL(18,2),BCH.MARRIED_FORECAST_QUANTITY)=0
		THEN '0'
		WHEN ifnull(h.NET_QTY,0)=0 AND CONVERT(DECIMAL(18,2),BCH.MARRIED_FORECAST_QUANTITY)>0
		THEN CONVERT(DECIMAL(18,2),BCH.MARRIED_FORECAST_QUANTITY)
		ELSE ABS(h.NET_QTY-CONVERT(DECIMAL(18,2),BCH.MARRIED_FORECAST_QUANTITY)) END >1
--AND BCH.TOP_DOWN_ADJUSTMENT > 0
--AND CONVERT(DECIMAL(18,2),BCH.MARRIED_FORECAST_QUANTITY) > BCH.FORECAST_QUANTITY_AFTER_UPLIFTS_BEFORE_ADJUSTMENT
--AND h.BULK_ORDER_QTY>0
--AND CASE WHEN [Bulk_Order].BULK_ORDER_QTY > 0 THEN (CASE WHEN H.BULK_ORDER_QTY > 0 THEN '1' ELSE '0' END) ELSE '0' END >0
--AND CASE WHEN [Outlier_Correction].Outlier_Correction > 0 THEN (CASE WHEN H.OUTLIER_CORRECTION_QTY > 0 THEN (CASE WHEN BCH.MARRIED_FORECAST_QUANTITY < H.NET_QTY THEN '1' ELSE '0' END) ELSE '0' END) ELSE '0' END = 1
--AND OUTLIER_CORRECTION_QTY>0
--AND CASE WHEN BCH.SKU_UPLIFT > 0 AND BCH.FORECAST_QUANTITY_AFTER_UPLIFTS_BEFORE_ADJUSTMENT < H.NET_QTY THEN '1' ELSE '0' END =1
--AND H.OOS_CORRECTION_QTY > 0
--AND H.PRODUCT_ID='20101599' --Bulk Order 
--AND H.PRODUCT_ID='80029119-100' --Outlier
--AND CASE WHEN BCH.TOP_DOWN_ADJUSTMENT > 1 THEN CASE WHEN CONVERT(DECIMAL(18,2),BCH.MARRIED_FORECAST_QUANTITY) > BCH.FORECAST_QUANTITY_AFTER_UPLIFTS_BEFORE_ADJUSTMENT AND H.NET_QTY > CONVERT(DECIMAL(18,2),BCH.MARRIED_FORECAST_QUANTITY) THEN '1' ELSE '0' END END = 1
ORDER BY H.PRODUCT_ID ASC, TO_CHAR(h.WEEK_START_DATE, 'IW') ASC